# Generated by Django 5.0.6 on 2024-08-31 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='applicant_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(max_length=10000)),
                ('application_status', models.CharField(default='Pending', max_length=50)),
                ('scheduled_time_slot', models.DateTimeField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('interview_panel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.interviewpanel')),
            ],
        ),
    ]
