# Generated by Django 5.0.6 on 2024-08-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applicant_data',
            new_name='ApplicantData',
        ),
    ]
