# Generated by Django 5.0.6 on 2024-08-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_applicant_data_applicantdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdata',
            name='feedback_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdata',
            name='interview_panel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interviewpanel'),
        ),
        migrations.AlterField(
            model_name='applicantdata',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdata',
            name='scheduled_time_slot',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
