# Generated by Django 5.0.6 on 2024-08-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_applicantdata_feedback_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='applicantdata',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
