# Generated by Django 5.0.6 on 2024-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_applicantdata_email_alter_applicantdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpanel',
            name='password',
            field=models.CharField(default='ABC//123', max_length=200),
        ),
    ]
