# Generated by Django 5.0.6 on 2024-09-01 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_interviewpanel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdata',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
